### ISSUE TITLE
With InfluxDB > 2, this plugin does not work anymore

### ISSUE THREAD

**Issue by orangecoding** [xtai/homebridge-influx-air#2]
As you're using influx-node working with influxdb 2 doesn't work anymore. I'm thinking about forking this and make it work by using https://github.com/influxdata/influxdb-client-js. 

Not sure if you have any plans to support influxdb 2 (a.k.a we can join forces)?

**Comment by xtai** [comment]
Hi @orangecoding, thanks for opening the issue.

No plan to support [influxdb-client-js](https://github.com/influxdata/influxdb-client-js) right now; feel free to fork or open PR to this repo. I think it will be a very straightforward change based on this [query.ts example](https://github.com/influxdata/influxdb-client-js/blob/master/examples/query.ts).
